export  interface Our_data {
    id: number,
    badge: boolean,
    badgeText: string,
    badgeColor: string,
    src: string,
    heading: string,
    newPrice: number,
    oldPrice_h2: boolean,
    oldPrice: number,
    shopBg: string,
}



export const OurProduct_Data: Our_data[] = [
    {
        id: 1,
        badge: true,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/product1.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        id: 2,
        badge: true,
        badgeText: "sales",
        badgeColor: "orange",
        src: "/products/product2.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: true,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        id: 3,
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/product3.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        id: 4,
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/product4.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        id: 5,
        badge: true,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/cat1.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        id: 6,
        badge: true,
        badgeText: "sales",
        badgeColor: "orange",
        src: "/products/card4.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: true,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        id: 6,
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/grid5.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        id: 7,
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/card5.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
]